version: "3.8"

services:
  postgres:
    image: postgres
    container_name: nextjs-auth-crud
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nextjs-auth-crud
    volumes:
      - data_postgres:/var/lib/postgresql/data

volumes:
  data_postgres:
